language: php

branches:
  only:
    - master
    - /^(?:(\d+)\.)?(?:(\d+)\.)?(\*|\d+)$/

services:
  - mysql

cache:
  apt: true
  directories:
    - $HOME/.composer/cache/files

addons:
  apt:
    packages:
      - nginx
  hosts:
    - wp.dev

notifications:
  email:
    on_success: never
    on_failure: change

services:
  - mysql
before_install:
  - mysql -e 'CREATE DATABASE myapp_test;'

php:
  - 7.1
  - 7.2
  - nightly

env:
  global:
    - COMPOSER_NO_INTERACTION=1
  matrix:
    - WP_VERSION=nightly
    - WP_VERSION=latest
    - WP_VERSION=4.9.3
    - WP_VERSION=4.8.5

matrix:
  allow_failures:
    - php: nightly
    - env: WP_VERSION=nightly
  fast_finish: true

before_install:
  - export PATH="$TRAVIS_BUILD_DIR/vendor/bin:$PATH"
  - export PATH="$TRAVIS_BUILD_DIR/bin:$PATH"
  - export TNW_TPL_DIR="$TRAVIS_BUILD_DIR/tpl"

install:
  - composer install --prefer-dist --no-suggest

before_script:
  - tnw-install-nginx
  - tnw-install-wordpress
  - tnw-prepare-codeception

script:
  ### Assert that WordPress is served at `http://wp.dev:8080`
  # Echo the WordPress Homepage source code
  - curl -vsf 'http://wp.dev:8080' &> /dev/stdout

  # Show the wp-config.php source code
  - cat /tmp/wordpress/wp-config.php

  # There should be nothing in the Nginx error log
  - cat /tmp/error.log

  # Display the WordPress version.
  - wp core version --path=/tmp/wordpress

